export const config = {
    PARTNER_SERVER_PORT: 4000,
    CONFIGURATION_SERVER_PORT: 4001,
    AUTHENTICATION_SERVER_PORT: 4002,
    PARTNER_SERVER_URL: "http://localhost:4000/",
    CONFIGURATION_SERVER_URL: "http://localhost:4001/",
    AUTHENTICATION_SERVER_URL: `http://localhost:4002/`
};

