name: Run tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_call:

jobs:
  test-local:

    runs-on: ubuntu-latest

    environment: test

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:local

  test-onedrive_litmus:

    runs-on: ubuntu-latest

    environment: test

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - run: docker build -t passport-proxy .
      - run: mkdir litmus_setup
      - run: cd litmus_setup
      - run: wget -O litmus.zip https://github.com/tolsen/litmus/archive/4d04ea01cd16574b8046d547aa5b773715372994.zip
      - run: unzip litmus.zip
      - run: docker build -t litmus litmus-4d04ea01cd16574b8046d547aa5b773715372994/
      - run: cd ..
      - run: rm -rf litmus_setup
      - run: docker run --name passport-proxy -d -e PROXY_TARGET=https://d.docs.live.net/ --network litmus_network passport-proxy
      - name: Run tests
        env:
          ONEDRIVE_CID: ${{ secrets.ONEDRIVE_CID }}
          ONEDRIVE_USERNAME: ${{ secrets.ONEDRIVE_USERNAME }}
          ONEDRIVE_PASSWORD: ${{ secrets.ONEDRIVE_PASSWORD }}
        run: npm run test:onedrive_litmus